### ISSUE TITLE
Problem with using bidirectional ports

### ISSUE THREAD

**Issue by Learner1729** [BehaviorTree/Groot#110]
Hello guys, I am new to BT and Groot, but noticed one issue, please kindly help me out with it.

When I am assigning any port as **InOut**, and then save the BT, it gets reflected properly on XML but **when I re-open** it I see the port **changes to Input port**, but in the xml it's still InOut port. So, after doing some changes when I save it again I have to keep in mind to revert the changes back, i.e. change the concern Input port to InOut port.

Please kindly help me out with this. Let me know if I am doing anything wrong. Thanks.

**Comment by facontidavide** [comment]
It looks like a bug. It needs to be investigated... by someone

**Comment by Learner1729** [comment]
Thank you sir for your immediate response.
