### ISSUE TITLE
wip, need help: use github actions instead of appveyor for CI

### ISSUE THREAD

**Issue by SubaruArai** [BehaviorTree/Groot#139]
I'm trying to implement github actions instead of appveyor, for CI.
The problem is, I couldn't build on windows.
Here's the [link](https://github.com/SubaruArai/Groot/tree/feature/use_github_actions) to the repo branch.
And there's the [link](https://github.com/SubaruArai/Groot/actions) to the output log.

I don't use msvc nor mingw, so any help is appreciated.
Below is what I understood:

1. both are problems of linking the dll. (the library component `behavior_tree_editor` is compiled)
2. msvc compiler succeeded to link `Groot`, but failed to compile the tests.
3. mingw failed to compile any executable.

**Comment by victorpaleologue** [comment]
I can have a look at your logs if you rebase your work and re-trigger the CI.
Why are you making this change, by the way ?

**Comment by SubaruArai** [comment]
> I can have a look at your logs if you rebase your work and re-trigger the CI. Why are you making this change, by the way ?

Never mind, I thought "since it's on github, why not use github actions?" at that time.
I can't really justify the switch now.
