### ISSUE TITLE
Real time monitor is not getting connected.

### ISSUE THREAD

**Issue by MayooranT** [BehaviorTree/Groot#153]
Even though i am able to load a tree in editor mode and properly register the nodes, real time monitor is not getting connected. The following error occurs when i click "connect".
`Was not able to connect to [tcp://localhost:1666]`
Can someone please help me on this issue?

**Comment by kundezui** [comment]
@MayooranT            Hello, I encountered the same error as you, did you solve it now?

**Comment by RitikJain12** [comment]
I am facing the same issue, I am using Ubuntu 20.04, ROS-noetic, ZMQ 4.1, and Behavior Tree v3.8 branch

**Comment by facontidavide** [comment]
Gentle reminder that:
- There is no plan to make Groot 1 compatible with BT.CPP 4.X
- This software is not maintained anymore.
- if anybody wants to fix it, I **may** review and merge the PR.

https://www.behaviortree.dev/groot

**Comment by shockley6668** [comment]
so how to connect

**Comment by facontidavide** [comment]
Assuming that you use BT.CPP 3.X, you should add `ZMQPublisher` to your application.
