### ISSUE TITLE
Add publisher/server port numbers as launch arguments

### ISSUE THREAD

**Issue by sea-bass** [BehaviorTree/Groot#166]
It would be very nice to be able to launch Groot with different publisher/server port numbers, for example:

```
ros2 run groot Groot --mode monitor --publisher_port 1668 --server_port 1669
```

My use case is the fact that I'm making a demo with behavior trees for high-level autonomy; however, the underlying example already uses the default ports (1666/1667) for the Nav2 BT navigator. So default options will always show the nav2 tree and not my example.

**Comment by Timple** [comment]
This would be nice in combination with #133
