### ISSUE TITLE
Segmentation fault when running  Groot

### ISSUE THREAD

**Issue by Euphoria7777** [BehaviorTree/Groot#174]
Thread 1 "Groot" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x6e00690061004d) at malloc.c:3102
3102    malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x6e00690061004d) at malloc.c:3102
#1  0x00007ffff7ef50fc in BT::TreeNodeManifest::~TreeNodeManifest() ()
    at /home/e/Groot/build/libbehavior_tree_editor.so
#2  0x00007ffff6ad4d5d in BT::BehaviorTreeFactory::BehaviorTreeFactory() ()
    at /opt/ros/noetic/lib/libbehaviortree_cpp_v3.so
#3  0x00007ffff7ef30fa in BuiltinNodeModels()::{lambda()#1}::operator()() const
    () at /home/e/Groot/build/libbehavior_tree_editor.so
#4  0x00007ffff7ef3447 in BuiltinNodeModels() ()
    at /home/e/Groot/build/libbehavior_tree_editor.so
#5  0x00007ffff7eafc8f in MainWindow::MainWindow(GraphicMode, QWidget*) ()
    at /home/e/Groot/build/libbehavior_tree_editor.so
#6  0x000055555556d35c in main ()

**Comment by facontidavide** [comment]
I think this happens because it is using the wrong dynamic library.

I tried to fix this mess with the latest commit https://github.com/BehaviorTree/Groot/commit/ee66489e6ea9ea3cbdd866d869aca8ea621035ce

Try recompiling and tell me if problem persists
