### ISSUE TITLE
 error: ‘zmq::send_flags’ has not been declared

### ISSUE THREAD

**Issue by liuyueChang** [BehaviorTree/Groot#178]

**Comment by yangshuo11** [comment]
I have met the same error when compiling the project

**Comment by yangshuo11** [comment]
back to the older version of "revert-157-Fix_Build", the project can be successfully compiled. I guess this error is caused by the incompatible version of zmq.

**Comment by lyd00116** [comment]
I met the same error when compling

**Comment by facontidavide** [comment]
I guess the safest solution would be to start using Conan to download the correct version of ZeroMQ
