### ISSUE TITLE
Crash when connecting

### ISSUE THREAD

**Issue by JonasTietz** [BehaviorTree/Groot#18]
We are trying to visualize a very simple behavior tree generated with https://github.com/BehaviorTree/BehaviorTree.CPP. When connecting with Groot to localhost, Groot crashes and we get the following error message:

```
setNativeLocks failed: resource not available
terminate called after throwing an instance of 'std::runtime_error'
  what():  Fatal error in [FlowScene::createConnection]: the nodeModel doesn't provide this portIndexOut
aborted
```

Both are compiled from their current master branch. We run on ubuntu 16.04.

Here is our code for the behavior tree:

```
#include <behaviortree_cpp/behaviortree_cpp/behavior_tree.h>
#include <behaviortree_cpp/loggers/bt_zmq_publisher.h>

using namespace BT;

NodeStatus SayHello() 
{
	std::cout << "Robot says Hello" << std::endl;
	return NodeStatus::SUCCESS;
}

int main()
{
    SequenceNode sequence_root("sequence");
    SimpleActionNode say_hello("action_hello", std::bind(SayHello) );
 
    sequence_root.addChild(&say_hello);

    NodeStatus status = NodeStatus::IDLE;

    PublisherZMQ publisher_zmq(&sequence_root);

    while(true)
    {
        status = sequence_root.executeTick();

        std::this_thread::sleep_for( std::chrono::milliseconds(1));
    }
    return 0;
}
```

Are we missing something or is this a problem in the upstream project?

**Comment by facontidavide** [comment]
Thank you for reporting, I will look into this issue tomorrow or next Monday

**Comment by facontidavide** [comment]
I found the bug. It was an issue in BehaviorTree.CPP that becomes apparent only when trees are created programmatically (discouraged) and not when the BehaviorTreefactory is used (recommended).

Nevertheless, I need to provide some warnings in PublisherZMQ and Groot to be sure that users are aware of the issue and that they know how to avoid it.

Thanks to this commit, your code should work now: 

https://github.com/BehaviorTree/BehaviorTree.CPP/commit/58ec28f4c9f885d1071ea5dd25b3f0a17163f617
