### ISSUE TITLE
Segfault after upgrading ros-noetic-behaviortree-cpp-v3 from 3.6.1 to 3.8.0

### ISSUE THREAD

**Issue by guilmant** [BehaviorTree/Groot#183]
Ubuntu 20.04, even with cloning and compiling current version of Groot, when trying to open editor mode, segmentation fault occurs.

**Comment by facontidavide** [comment]
It is probably try to link to the wrong version of the library. Make sure that, when recompiling, the version is the one in the submodule folder https://github.com/BehaviorTree/Groot/tree/master/depend

**Comment by guilmant** [comment]
I deleted the full Groot folder and followed the Linux compilation instructions.

Could you please provide some more detail for making sure the correct version is linked? Thank you!

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/203358030-e43f6366-5d01-47c0-a5ce-a5bf28534dc5.png)

**Comment by guilmant** [comment]
Okay, for me `cmake ..` does not give `BehaviourTree.CPP submodule found`.

Could you tell me, which file cmake-gui changes or adds the path info to?

**Comment by guilmant** [comment]
Or could you provide the possibility to downgrade the deb package to ros-noetic-behaviortree-cpp-v3 3.6.1?
apt only seems to be able to provide 3.8 unfortunately

**Comment by facontidavide** [comment]
@guilmant I am 95% sure that Groot works find with 3.8 when it is a submodule. I will check again
