### ISSUE TITLE
BehaviorTree.CPP 4.0 compability

### ISSUE THREAD

**Issue by grammers** [BehaviorTree/Groot#188]
I'm running BehaviorTree.CPP version 4.0, due to braking changes in that Groot is not compiling.
I know that this is a project to fix and is probably best done in a 4.0 compliment branch so I bring it up in the hope someone take the task (or perhaps is working on it)

**Comment by facontidavide** [comment]
Groot 1.0 will NEVER support BehaviorTree 4.0, not in terms of compiling nor as general support of the differnt XML syntax. reasons are described in the README

I willfully abandoned this project in favor of Groot 2, that you can find here: https://www.behaviortree.dev/groot

If you or anybody else need support, you can contact me privately here: dfaconti@aurynrobotics.com
