### ISSUE TITLE
Groot output contains incorrect XML comments

### ISSUE THREAD

**Issue by altacch** [BehaviorTree/Groot#19]
Hi @facontidavide ,
in the XML output of the current version of Groot there are comments of the form
```<!--------------------------------------->```
Unfortunately this does not appear to be valid XML. It is flagged as invalid by Emacs, it is rejected by the XML parsing library we are using in [Carve](https://github.com/CARVE-ROBMOSYS/BTCompiler) and also by an [online validator](https://xmlvalidation.com/). In fact it seems that XML comments cannot contain the string "--" unless it marks the end comment tag.
Could you please change these comments to make them XML-compliant?

**Comment by facontidavide** [comment]
yes, I noticed that some libraries might find that annoying... I will fix it
