### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by v-lopez** [BehaviorTree/Groot#20]
Some things we discussed last day and other ideas:

- [x] View node names in Groot
- [x] (Ver 3) view output ports
- [x] View port descriptions
- [x] (minor nice to have) highlight connected ports. I could give this a look once they are visible.
- [ ] User defined categories for Nodes (once we have 50+ nodes, it would be nice to group them into Grasping/Navigation/...)
- [] Add Custom Decorators

I can make one issue per idea, I didn't want to spam without warning.

**Comment by facontidavide** [comment]
https://github.com/BehaviorTree/Groot/projects/1

I don't know if I will have much time for the last one, but I will surely focus on the others

**Comment by v-lopez** [comment]
Adding one item for the wishlist: Adding custom decorators in the TreeNode Editor. 

As an example, I have a custom decorator that is an templated Iterator, it works like a "Repeat" but it executes it's leaf as many times as items are in it's input container, and on each iteration outputs the iterated item to the blackboard.

Since it's templated, I'll need to make custom version such as you've done with BlackboardCheck* in `ver_3`.

**Comment by facontidavide** [comment]
more or less all the feature, with exception of the Custom categories, is implemented. Take a look

**Comment by v-lopez** [comment]
Great work on all those!

I believe one feature is missing (that was not on this list), the ability to connect internal/external ports for a subtree from Groot.

**Comment by facontidavide** [comment]
no, the feature is there. I just simplified the syntax to make it more consistent. I will prepare a video tutorial to show how it works.

**Comment by hlzl** [comment]
> no, the feature is there. I just simplified the syntax to make it more consistent. I will prepare a video tutorial to show how it works.

Any updates on the video/tutorial? I would be interested as well :)

**Comment by facontidavide** [comment]
Hopefully the next week...

**Comment by facontidavide** [comment]
closing this issue because of my limited bandwidth
