### ISSUE TITLE
Compilation issue with Qt

### ISSUE THREAD

**Issue by Masadow** [BehaviorTree/Groot#27]
I could not compile unless I set the following two lines to OFF in QtNodeEditor/CMakeLists.txt

set(CMAKE_DISABLE_IN_SOURCE_BUILD ON)
set(CMAKE_DISABLE_SOURCE_CHANGES  ON)

I don't know what was the purpose of disabling it but it makes the line qt5_add_resources to crash for me.

**Comment by facontidavide** [comment]
I will check this out. Since this is a third party library (that I modified heavily) I am not able to give you an answer right now

**Comment by facontidavide** [comment]
How are you compiling it? I am trying to reproduce the error

**Comment by facontidavide** [comment]
@Masadow ok, I understand what is going on.

Basically, the library discourage people from compiling  in the same directory directory of source.

This is such a bad practice that many libraries, including QtNodeEditor, forbid it (for your own  good).

This is such a bad practice that CMake itself provide ready to use parameters (the one you are turning OFF) to deal with this.

I __never__ build in-source, so I didn't even notice that I couldn't do it :)

For more information: https://stackoverflow.com/questions/45518317/in-source-builds-are-not-allowed-in-cmake
