### ISSUE TITLE
Malformed behaviorTree

### ISSUE THREAD

**Issue by Masadow** [BehaviorTree/Groot#30]
Hey, so I've just updated to the latest and now, whenever I try to save (even from a fresh new xml created from Groot), it says malformed behavior tree.

**Comment by facontidavide** [comment]
Please share the file with me and I will try to address this as soon as
possible

**Comment by Masadow** [comment]
Steps :

Run Groot
Click Start
Click Save Tree -> Bug

**Comment by facontidavide** [comment]
Well, that is NOT a bug, since your tree IS malformed.

ControlNodes, Decorators and Root need at least 1 child. You have a handy semaphore to know if your tree is malformed.


![image](https://user-images.githubusercontent.com/2822888/55341426-e54f6200-54a6-11e9-86c6-0ec094d43ccb.png)

**Comment by Masadow** [comment]
Ok, I'll send you an email with my tree then, it's working perfectly when I load it via the library but failing with Groot

**Comment by facontidavide** [comment]
Fixed :)

You must remove from your file the node __\<Root\>__ that was accidentally generated in a previous version.
