### ISSUE TITLE
Syntax not recognized by Groot

### ISSUE THREAD

**Issue by Masadow** [BehaviorTree/Groot#33]
Hi, is it an error in v3 to have a TreeNodeModel like :

        <Action ID="faceTo">
            <Parameter label="target_key" default="target"/>
        </Action>

It seems to work fine but Groot is not recognizing it and therefore not displaying the port.

If that's an error to write such a TreeNodeModel, how should I be supposed to convert it properly to ensure the perfect same behavior ?

**Comment by facontidavide** [comment]
yes, this syntax is not supported anymore.
New format is explained here https://www.behaviortree.dev/xml_format/

- __Parameter__ are not __input ports__. 
- There is no label but ID.
