### ISSUE TITLE
Crash open Groot after minimizing

### ISSUE THREAD

**Issue by GiovanniBottino** [BehaviorTree/Groot#34]
Hi @facontidavide ,
i found this bug of Groot. When the application is minimized and i try to reopen it, it crashes.
Tracking the execution from terminal i got this error:
>> terminate called after throwing an instance of 'std::runtime_error' what():  There is already a Tab named BehaviorTree

**Comment by MarcelSoler** [comment]
Hi there! the same happened to me.

**Comment by facontidavide** [comment]
Hi, I will try to fix it today or tomorrow at worst.

**Comment by MarcelSoler** [comment]
Nice!! Works perfectly now.
