### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by LeonJung** [BehaviorTree/Groot#35]
Hi,
thanks for sharing your great work here, first of all.

I got error message during compiling the source with $ make.

[  1%] Automatic MOC, UIC and RCC for target tinyxml2_v7
[  1%] Built target tinyxml2_v7_autogen
[  3%] Built target tinyxml2_v7
[  4%] Automatic MOC, UIC and RCC for target behaviortree_cpp_v3
[  4%] Built target behaviortree_cpp_v3_autogen
[  4%] Linking CXX shared library ../../lib/libbehaviortree_cpp_v3.so
/usr/bin/ld: cannot find -ldw
collect2: error: ld returned 1 exit status
depend/BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/build.make:823: recipe for target 'lib/libbehaviortree_cpp_v3.so' failed
make[2]: *** [lib/libbehaviortree_cpp_v3.so] Error 1
CMakeFiles/Makefile2:327: recipe for target 'depend/BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/all' failed
make[1]: *** [depend/BehaviorTree.CPP/CMakeFiles/behaviortree_cpp_v3.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

what can I do for solving.

* My settings is Ubuntu 18.04 i9

**Comment by facontidavide** [comment]
I should update the readme...

install libdw

      sudo apt install libdw-dev

**Comment by LeonJung** [comment]
@facontidavide 

it seems working
Thanks.
