### ISSUE TITLE
error: ‘QSignalBlocker’ does not name a type

### ISSUE THREAD

**Issue by paribartann** [BehaviorTree/Groot#38]
It sends out a compilation error while doing the 'make'
Following error:
Groot/bt_editor/mainwindow.cpp:908:11: error: ‘QSignalBlocker’ does not name a type
     const QSignalBlocker blocker( this );

My qmake version:
QMake version 3.1
Using Qt version 5.12.3 in /opt/Qt/5.12.3/gcc_64/lib

Am I  doing anything wrong?
Thank you!

**Comment by facontidavide** [comment]
Hi, 

you need a newer version of Qt since QSignalBlocker was introduced in Qt 5.3

https://doc.qt.io/qt-5/qsignalblocker.html

**Comment by paribartann** [comment]
Do I install the binaries for QT or put in my cloned Groot folder? I have the latest Qt but it's still complaining. Would you mind helping in this regard? I went through other issues but couldn't find the way through the problem.

**Comment by facontidavide** [comment]
If it is complaining , you are using somehow the wrong version of Qt, thee is no other explanation.
If you are using QtCreator, double check the current kit.
This is not a problem of Groot, it is your Qt configuration that is wrong.

![image](https://user-images.githubusercontent.com/2822888/58594377-bfa7c480-826d-11e9-8ce5-de531794b9b0.png)
