### ISSUE TITLE
BT Load does not clear previously existing nodes

### ISSUE THREAD

**Issue by StefanoSoffiaUTRC** [BehaviorTree/Groot#4]
Minor issue.
If I load a BT *A* and after it I load a BT *B*, then nodes from *A* (e.g. `SubTree` and `Action`) are still listed in the node browser (on the left).

**Comment by facontidavide** [comment]
I still need to decide if that is a feature or a bug ;)

Today I pushed many changes, let me think about it a little more...

**Comment by facontidavide** [comment]
![image](https://user-images.githubusercontent.com/2822888/47997706-16e11e80-e0fd-11e8-8adf-ef7f8ee53b58.png)

Fixed. Thanks for the suggestion
