### ISSUE TITLE
cannot make realtime monitor, log replay work

### ISSUE THREAD

**Issue by MarcelSoler** [BehaviorTree/Groot#41]
I have two issues while using Groot:

1. I have generated a bt_trace.fbl file [bt_trace.zip](https://github.com/BehaviorTree/Groot/files/3416589/bt_trace.zip),  like the tutorials:
 `FileLogger logger_file(tree, "bt_trace.fbl");` 
And I'm using a custom bt.

But, when I try to open it bt_trace.fbl with Groot, it crashes sending the following error:

```
Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp/flatbuffers/flatbuffers.h:1988: flatbuffers::Verifier::Verifier(const uint8_t*, size_t, flatbuffers::uoffset_t, flatbuffers::uoffset_t, bool): Assertion `size_ < FLATBUFFERS_MAX_BUFFER_SIZE' failed.
Aborted (core dumped)
```

2. I've been trying to real time monitor with Groot (last master version), however it doesn't work neither in my own pc (localhost) or the robot with the correct ip . 

![image](https://user-images.githubusercontent.com/17928622/61622412-0239bc00-ac75-11e9-84ed-6f4e987c0dd2.png)

![image](https://user-images.githubusercontent.com/17928622/61622100-6f991d00-ac74-11e9-8106-a72693ebddc9.png)

Usefull info:
*  I have lib zeromq installed
* I have compiled Groot like linux compilation intructions.
* I am using ros melodic with ubuntu 18.04

Any help will be apreciated.

**Comment by hlzl** [comment]
Are you creating the necessary publisher for real-time monitoring with `PublisherZMQ publisher_zmq(tree);`?

**Comment by MarcelSoler** [comment]
Thanks, working now!

**Comment by kaorusha** [comment]
hi, i encountered the same problem (cannot make realtime monitor and log replay work). The tutorial example crossdoor_trace.fbl can be replayed correctly. but can't replay the log from my custom bt: [,](https://drive.google.com/file/d/1-c5c45WOt16oD8foOyOjrE-EIoJA9JyH/view?usp=sharing) the terminal shows the following error: terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)

any feedback is appreciated, thank you in advance.
additional information:

1. lib zeromq installed, and i have `PublisherZMQ publisher_zmq(tree);`
2. compiled Groot with cmake version 3.10.2
3. ros melodic with ubuntu 18.04
4. i use custom condition and action node, and the BT::StdCoutLogger and BT::MinitraceLogger is working

**Comment by RitikJain12** [comment]
I am facing the same issue with ros noetic
