### ISSUE TITLE
Support blackboard

### ISSUE THREAD

**Issue by StefanoSoffiaUTRC** [BehaviorTree/Groot#5]
How to model interactions with the blackboard?
The syntax used in [this tutorial](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/docs/tutorial_C_blackboard.md) seems to suggest that GRoot needs to be extended with an additional custom node:

```
            <SetBlackboard key="OtherGoal" value="-1;3;0.5" />
            <MoveBase  goal="${OtherGoal}" />
```

As an alternative, I can model this as a custom `Action` node with the two parameters `Key` and `Value`, but this does not seem to be currently supported by GRoot.

**Comment by facontidavide** [comment]
Yes, I have to add the Builtin action __SetBlackboard__

**Comment by facontidavide** [comment]
fixed
