### ISSUE TITLE
Very easy to create invalid XML.

### ISSUE THREAD

**Issue by unvestigate** [BehaviorTree/Groot#67]
Open Groot and create this (admittedly nonsense) BT:

![image](https://user-images.githubusercontent.com/20167696/77074875-22836b80-69fa-11ea-992c-9b127124a048.png)

Save the tree. This results in the following valid XML:

```
<?xml version="1.0"?>
<root main_tree_to_execute="BehaviorTree">
    <!-- ////////// -->
    <BehaviorTree ID="BehaviorTree">
        <Sequence>
            <AlwaysSuccess/>
        </Sequence>
    </BehaviorTree>
    <!-- ////////// -->
    <TreeNodesModel/>
    <!-- ////////// -->
</root>
```

Now add another node as a sibling to the Sequence node, like this:

![image](https://user-images.githubusercontent.com/20167696/77075090-7aba6d80-69fa-11ea-830c-909de722331e.png)

Again, save the file and the produced XML will look like this:

```
<?xml version="1.0"?>
<root main_tree_to_execute="BehaviorTree">
    <!-- ////////// -->
    <BehaviorTree ID="BehaviorTree">
        <Root>
            <AlwaysFailure/>
            <Sequence>
                <AlwaysSuccess/>
            </Sequence>
        </Root>
    </BehaviorTree>
    <!-- ////////// -->
    <TreeNodesModel/>
    <!-- ////////// -->
</root>
```

If you shut Groot down and try to load the second file it will complain about the Root node and ask you to remove it. Regardless if you remove it or not, the app will only show you a part of the original BT.

**Comment by unvestigate** [comment]
I had a look in MainWindow::saveToXML() and found this:

```
auto abs_root = abs_tree.rootNode();
if( abs_root->children_index.size() == 1 &&
    abs_root->model.registration_ID == "Root"  )
{
    // mofe to the child of ROOT
    abs_root = abs_tree.node( abs_root->children_index.front() );
}
```

After that it proceeds to serialize abs_root. So this tells me that if we have a node with registration ID "Root" and exactly one child, we skip the node (thus leaving it out of the data) and move to its first node. This poses a problem when the root node has multiple children, as the "Root" node which apparently is supposed to be left out gets included in the data.

Why was the saving code set up like this? Why not just start serializing the root node and all of its children recursively? This effectively prevents Groot from ever having trees where the root node has more than one child.

**Comment by renan028** [comment]
Hi @unvestigate ,
I am working with Groot also.
I didn't understand the issue. BT's root must have one and only one child. You are not supposed to create a BT like the second image. 
Do you think Groot should not allow the connection?

**Comment by unvestigate** [comment]
I will admit I haven't had much practical experience working with BTs (that's why I am here now) so excuse my ignorance. Why would a tree where the root has multiple children not be possible?

I am not talking about the exact tree in my example, but some other two nodes as children of root.

Finally, if such a tree truly is not allowed, we should probably not allow creating such a tree in Groot.

**Comment by renan028** [comment]
> Why would a tree where the root has multiple children not be possible?

Because then the root would not be the root, but a Control Node instead. You will have to create a logic on how it "ticks" its children, and that logic is for Control Nodes. You can have a look here [Theory](https://en.wikipedia.org/wiki/Behavior_tree_(artificial_intelligence,_robotics_and_control))

> Finally, if such a tree truly is not allowed, we should probably not allow creating such a tree in Groot.

Yes. I think that is an issue.

**Comment by unvestigate** [comment]
I looked around the net a bit for examples of BTs and it seems they all have a sequence or selector node as the sole child of the root. This makes sense when you consider how the tree will be traversed. Is this what you were referring to @renan028 ?

So maybe we should just prevent Groot from trying to save such a tree? There is already the validation with the green/red icon...

**Comment by unvestigate** [comment]
Ah, I see you just answered :) Thanks!

**Comment by facontidavide** [comment]
it is indeed a bug. Something like this is not supposed to happen (the graphical editor must not allow you to attach multiple children to Root!

I will need to address this.

**Comment by facontidavide** [comment]
FYI, in the XML there is no "Root". 

That is something that is needed only in Groot for technical reasons.

**Comment by unvestigate** [comment]
> FYI, in the XML there is no "Root".

Except when there is :)

**Comment by facontidavide** [comment]
fixed
