### ISSUE TITLE
realtime monitor and log replay issue

### ISSUE THREAD

**Issue by liuxin00738** [BehaviorTree/Groot#7]
Hi,
Recently I installed Groot and I am trying to do a realtime monitor and log replay using groot and the BehaviorTree.cpp/Examples/t05_crossdoor.cpp. I have lib zeromq installed. However, I am having several issues. 

First, for the master branch, the monitor does not show the graph, but only telling that some msgs are received. the log replay, on the otherhand, will not change color of nodes and edges. I am also having issues with the xml format. Seems that it does not recognize subtree type, and errors out. I have to modify the crossdoor example so the subtree is  insert in place. Also, the first xml format in this [link](https://behaviortree.github.io/BehaviorTree.CPP/tutorial_A_create_trees/) does not work for groot.

Second, it seems that the dev branch's subtree monitor and log replay works. However, I need to open the tree first with the editor, then switch to monitor/log mode. I am not sure this is a bug or feature.
I maybe using it wrong. Any suggestions?

Best Regards,

**Comment by facontidavide** [comment]
I will look into this soon. Cheers

**Comment by facontidavide** [comment]
> First, for the master branch, the monitor does not show the graph, but only telling that some msgs are received. the log replay, on the other hand, will not change color of nodes and edges.

There were several issues that I fixed. It should work now.

>  I am also having issues with the xml format. Seems that it does not recognize subtree type, and errors out. I have to modify the crossdoor example so the subtree is insert in place.

You are right, I have to update the documentation.

> Second, it seems that the dev branch's subtree monitor and log replay works. However, I need to open the tree first with the editor, then switch to monitor/log mode. I am not sure this is a bug or feature.

A bug I fixed. Dev branch is obsolate

**Comment by facontidavide** [comment]
Feel free to open again the issue if you have any further problem

**Comment by liuxin00738** [comment]
It worked! Thanks a lot!
