### ISSUE TITLE
Groot crashes when trying to load a new models and removing previously loaded nodes

### ISSUE THREAD

**Issue by abhijeet2241994** [BehaviorTree/Groot#74]
This is a recurrent problem I keep getting. 
I load a workflow , add subtrees to it.
Next I try to load a new workflow without saving the earlier one. 
I get a message box asking " Do you want to remove previously loaded custom nodes?"
I say Yes.
Groot crashes after that. 
It does not crash if I say No.
Maybe some issue with the CleanPreviousModels function from utils.cpp which is called in LoadFromXML function in mainwindow.cpp?

**Comment by facontidavide** [comment]
It should be fixed now.
