### ISSUE TITLE
Install dependencies with rosdep (in case of catkin ws)

### ISSUE THREAD

**Issue by Bitfroest** [BehaviorTree/Groot#77]
In case of ROS, All the dependencies should be installed with rosdep. This includes also the following:
```
sudo apt install qtbase5-dev libqt5svg5-dev libzmq3-dev libdw-dev
```
-> Thus, we should include those in `package.xml`.

e.g. rosdep dependencies get installed with
```
rosdep install --from-paths src --ignore-src --rosdistro=melodic -y -r
```

Avoids that every user have to install them manually.

**Comment by facontidavide** [comment]
good point
