### ISSUE TITLE
subtree sequence

### ISSUE THREAD

**Issue by liuxin00738** [BehaviorTree/Groot#8]
Hi Davide,

I find a new issue of the groot. If I have more than one sub-tree for a sequence, the groot seems to put the subtree in the wrong order.

**Comment by facontidavide** [comment]
Thanks for reporting. I will add the unit test and fix the issue tomorrow

**Comment by facontidavide** [comment]
Can you share a XML file to reproduce this?

**Comment by liuxin00738** [comment]
[tree.tar.gz](https://github.com/BehaviorTree/Groot/files/2609305/tree.tar.gz)

Hi Davide,

Please see the attached xml and groot picture. Please notice that both the subtree and the sequence node are in wrong order. It seems to be related to the name or string I give them. And if I change the name sometimes the order is correct. But the one I send is wrong all the time for my machine.

**Comment by facontidavide** [comment]
Ok, I see. the error can be reproduced easily with the simplified tree<root main_tree_to_execute = "MainTree">

```XML
    <BehaviorTree ID="PickingItem">
            <Action ID = "AdjustTCPOrientation"/>
    </BehaviorTree>
    <BehaviorTree ID="MoveToPredefinedPoint">
            <Action ID = "LinearMove"/>
    </BehaviorTree>

    <BehaviorTree ID="MainTree">
        <Sequence name="move from bin A to bin B">
            <SubTree ID = "MoveToPredefinedPoint"/>
            <SubTree ID = "PickingItem"/>
        </Sequence>
    </BehaviorTree>
</root>
```
I will fix it today.
By the way, you also gave me an idea for an improvement in the visualization ;)

**Comment by facontidavide** [comment]
```    <BehaviorTree ID="PickingItem">            <Action ID = "AdjustTCPOrientation"/>    </BehaviorTree>    <BehaviorTree ID="MoveToPredefinedPoint">            <Action ID = "LinearMove"/>    </BehaviorTree>    <BehaviorTree ID="MainTree">        <Sequence name="move from bin A to bin B">            <SubTree ID = "MoveToPredefinedPoint"/>            <SubTree ID = "PickingItem"/>            <!-- <SubTree ID = "Scan"/> -->        </Sequence>    </BehaviorTree></root>```

**Comment by facontidavide** [comment]
Ok, I found the bug (it was a nasty one) and I have also made some additional changes.

Test the __dev__ branch if you can. 

I also changed the way nodes with names are displayed: 

![image](https://user-images.githubusercontent.com/2822888/48943069-390ed500-ef22-11e8-8bb5-868d6b0b87f5.png)

**Comment by facontidavide** [comment]
By the way, I also noticed thanks to your screenshot a small error in the auto-arrange function. I correct it.
See the before and after pictures
![screenshot from 2018-11-22 13-42-04](https://user-images.githubusercontent.com/2822888/48949947-e93c0800-ef39-11e8-89c4-995dafbfa75f.png)
![selection_100](https://user-images.githubusercontent.com/2822888/48949949-eccf8f00-ef39-11e8-9651-e421f07eeea9.png)
