### ISSUE TITLE
Fail to build Groot (my system: Ubuntu 18.04, Ros2 Dashing)

### ISSUE THREAD

**Issue by phunghoabk** [BehaviorTree/Groot#83]
I try to build Groot as the guideline step by step exactly, but I got errors. Please help, I am new to ROS. Thank you.
Here is the error messages:

In file included from /home/phung/BehaviorTree/Groot/bt_editor/models/BehaviorTreeNodeModel.hpp:16:0,
                 from /home/phung/BehaviorTree/Groot/bt_editor/models/BehaviorTreeNodeModel.cpp:1:
/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.h:11:10: fatal error: behaviortree_cpp_v3/bt_factory.h: No such file or directory
 #include <behaviortree_cpp_v3/bt_factory.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/behavior_tree_editor.dir/build.make:94: recipe for target 'CMakeFiles/behavior_tree_editor.dir/bt_editor/models/BehaviorTreeNodeModel.cpp.o' failed
make[2]: *** [CMakeFiles/behavior_tree_editor.dir/bt_editor/models/BehaviorTreeNodeModel.cpp.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/behavior_tree_editor.dir/all' failed
make[1]: *** [CMakeFiles/behavior_tree_editor.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by facontidavide** [comment]
I will update the compilation instructions on the README.

**Comment by Brudasoe** [comment]
I've had similar issue, reverting changes in e4863d546d851c9ff13f4a7d1a5f1386327c384a seemed to help

**Comment by doisyg** [comment]
Same here, failure to build under Ubuntu 18.04:

> /home/gd/Groot/bt_editor/bt_editor_base.cpp: In lambda function:
> /home/gd/Groot/bt_editor/bt_editor_base.cpp:195:38: error: ‘SubtreeNode’ is not a member of ‘BT’
>          factory.registerNodeType<BT::SubtreeNode>("Root");
>                                       ^~~~~~~~~~~
> /home/gd/Groot/bt_editor/bt_editor_base.cpp:195:38: note: suggested alternative: ‘TreeNode’
>          factory.registerNodeType<BT::SubtreeNode>("Root");
>                                       ^~~~~~~~~~~
>                                       TreeNode
> /home/gd/Groot/bt_editor/bt_editor_base.cpp:195:38: error: ‘SubtreeNode’ is not a member of ‘BT’
> /home/gd/Groot/bt_editor/bt_editor_base.cpp:195:38: note: suggested alternative: ‘TreeNode’
>          factory.registerNodeType<BT::SubtreeNode>("Root");
>                                       ^~~~~~~~~~~
>                                       TreeNode
> /home/gd/Groot/bt_editor/bt_editor_base.cpp:195:57: error: no matching function for call to ‘BT::BehaviorTreeFactory::registerNodeType<<expression error> >(const char [5])’
>  actory.registerNodeType<BT::SubtreeNode>("Root");
>                                                 ^
> In file included from /home/gd/Groot/bt_editor/bt_editor_base.h:11:0,
>                  from /home/gd/Groot/bt_editor/bt_editor_base.cpp:1:
> /home/gd/Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp_v3/bt_factory.h:193:10: note: candidate: template<class T> void BT::BehaviorTreeFactory::registerNodeType(const string&)
>      void registerNodeType(const std::string& ID)
>           ^~~~~~~~~~~~~~~~
> /home/gd/Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp_v3/bt_factory.h:193:10: note:   template argument deduction/substitution failed:
> /home/gd/Groot/bt_editor/bt_editor_base.cpp:195:57: error: template argument 1 is invalid
>  actory.registerNodeType<BT::SubtreeNode>("Root");
>

**Comment by phunghoabk** [comment]
> I've had similar issue, reverting changes in [e4863d5](https://github.com/BehaviorTree/Groot/commit/e4863d546d851c9ff13f4a7d1a5f1386327c384a) seemed to help

I reverted the Cmakelists.txt following this comment, and when I build the code, it has a new bug. Anyone can help. Thank you.

/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp: In lambda function:
/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp:195:38: error: ‘SubtreeNode’ is not a member of ‘BT’
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                      ^~~~~~~~~~~
/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp:195:38: note: suggested alternative: ‘TreeNode’
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                      ^~~~~~~~~~~
                                      TreeNode
/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp:195:38: error: ‘SubtreeNode’ is not a member of ‘BT’
/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp:195:38: note: suggested alternative: ‘TreeNode’
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                      ^~~~~~~~~~~
                                      TreeNode
/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp:195:57: error: no matching function for call to ‘BT::BehaviorTreeFactory::registerNodeType<<expression error> >(const char [5])’
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                                         ^
In file included from /home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.h:11:0,
                 from /home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp:1:
/home/phung/BehaviorTree/Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp_v3/bt_factory.h:193:10: note: candidate: template<class T> void BT::BehaviorTreeFactory::registerNodeType(const string&)
     void registerNodeType(const std::string& ID)
          ^~~~~~~~~~~~~~~~
/home/phung/BehaviorTree/Groot/depend/BehaviorTree.CPP/include/behaviortree_cpp_v3/bt_factory.h:193:10: note:   template argument deduction/substitution failed:
/home/phung/BehaviorTree/Groot/bt_editor/bt_editor_base.cpp:195:57: error: template argument 1 is invalid
         factory.registerNodeType<BT::SubtreeNode>("Root");
                                                         ^
CMakeFiles/behavior_tree_editor.dir/build.make:214: recipe for target 'CMakeFiles/behavior_tree_editor.dir/bt_editor/bt_editor_base.cpp.o' failed
make[2]: *** [CMakeFiles/behavior_tree_editor.dir/bt_editor/bt_editor_base.cpp.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/behavior_tree_editor.dir/all' failed
make[1]: *** [CMakeFiles/behavior_tree_editor.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by facontidavide** [comment]
I will help today. Sorry for the late reply

**Comment by veeraragav** [comment]
I have the same problem.

**Comment by veeraragav** [comment]
I have the same problem. Please help!

**Comment by facontidavide** [comment]
### Groot master branch  works only with BehaviorTree.CPP master branch.

I am going to realse soon a new version of BehaviorTree.CPP, but as a workaroud, you may dowload BT.CPP with git and put it in the same workspace where you are building Groot.

**Comment by facontidavide** [comment]
I have submitted the new version (3.5) and it will be available for download in few days.

That will not any problem with Groot, In the meanwhile, you may use the master branch of BehaviorTree.CPP
