### ISSUE TITLE
Custom ControlNode support

### ISSUE THREAD

**Issue by Sarath18** [BehaviorTree/Groot#84]
Hello, I was wondering why custom ControlNodes cannot be created using Groot. Navigation2 uses a lots of custom BT nodes including custom control nodes. Adding the control node structure manually to the TreeNodesModel helps in visualizing the behavior trees. But these trees when exported from Groot cannot be loaded using the BehaviorTree.CPP library. I believe this is again because of the restriction in the library to create custom control nodes. Correct me if I am wrong.

Can you please verify if this design is by choice and a feature rather than an issue? If yes, why?

Adding custom ControlNodes support to Groot will be really helpful for creating, modifying, editing BT nodes using custom ControlNodes (especially in navigation2). The previous discussion on adding groot support for behavior trees in navigation2 can be found [here](https://github.com/ros-planning/navigation2/issues/1700)

**Comment by facontidavide** [comment]
> I was wondering why custom ControlNodes cannot be created using Groot.

I think I can change this.

**Comment by facontidavide** [comment]
It should work now
