### ISSUE TITLE
Adding an input port with the name ID should cause a GUI error

### ISSUE THREAD

**Issue by esromneb** [BehaviorTree/Groot#85]
An input/output/inout port with the name `ID` is not allowed.  This is a reserved word.  Doing this causes the output XML to be broken.  The GUI should not allow this.

In this example I have left the default value for `ID` blank.  This results in an illegal `Action` node
```
<?xml version="1.0"?>
<root main_tree_to_execute="BehaviorTree">
    <!-- ////////// -->
    <BehaviorTree ID="BehaviorTree">
        <Sequence>
            <Action ID="actionOK" most_names_ok=""/>
            <Action ID=""/>
        </Sequence>
    </BehaviorTree>
    <!-- ////////// -->
    <TreeNodesModel>
        <Action ID="actionBroken">
            <input_port name="ID">this is a reserved value and should not be allowed</input_port>
        </Action>
        <Action ID="actionOK">
            <input_port name="most_names_ok"/>
        </Action>
    </TreeNodesModel>
    <!-- ////////// -->
</root>
```

**Comment by facontidavide** [comment]
great point

**Comment by esromneb** [comment]
Thanks for this great tool and all of your hard work.  I'm just learning how to use Behavior Trees myself.  Do you prefer issues or pull requests if I find any other small issues?

**Comment by facontidavide** [comment]
pull request are always welcome... if well tested ;)

**Comment by facontidavide** [comment]
Fixed
