### ISSUE TITLE
Right clicking on category item (Action,Condition,Control...) and choosing remove crashes

### ISSUE THREAD

**Issue by esromneb** [BehaviorTree/Groot#87]
Doing a right click on any of Action,Condition,Control,Decorator,SubTree and choosing remove causes an instant crash.  
```bash
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
[1]    31602 abort (core dumped)  ./Groot
```

This occurs with an empty tree.

I think I have a working PR to fix this I will submit in about 5 mins

**Comment by facontidavide** [comment]
thanks for fixing it
![thank_you](https://user-images.githubusercontent.com/2822888/82534366-50457780-9b45-11ea-8b16-071085130aa2.gif)

**Comment by esromneb** [comment]
You're welcome!
